version: '3'

services:
    db:
        image: postgres:latest
        volumes:
            - db_data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_DB: app_app
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"

    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
        depends_on:
            - db
volumes:
    db_data:
